### ISSUE TITLE
Search Suggestions failing

### ISSUE THREAD

**Issue by iredmedia** [ticketevolution/ticketevolution-php#130]
The following function is failing with a 500 (Reason phrase) error:

```
$results = Tevo::listSearchSuggestions([
    'entities' => ['performers'],
    'fuzzy' => true,
    'q' => $query,
]); return $results;
```

If i try to create the request as stated in the docs with guzzle, explicitly stating the URL, passing in an authentication`/v9/searches/suggestions?entities%5B%5D=events&entities%5B%5D=performers&entities%5B%5D=venues&limit=5&q=yankee`

It rewrites the %5B%5D to %5B0%5D, %5B1%5D respectively. This seems to be the issue, as the request just returns some empty but successful data if I omit the entities.

I've verified that the supplied url works via curl, could this be because of Guzzles serializer?

**Comment by iredmedia** [comment]
bump, is anyone else experiencing this issue?

**Comment by jwcobb** [comment]
I can replicate and agree it is because of the way Guzzle and http_build_query() encode things. I don't believe there is an easy work around for this and I think it makes more sense to try and get the endpoint adjusted to accept a comma delimited list instead of an array so I will open a ticket for that with the engineering team.

**Comment by iredmedia** [comment]
Thanks so much. I'm using entities2 and guzzle pooling to work around. I
can send example code if you'd like
